server:
  port: 8888
  servlet:
    context-path: /furniture

web:
  upload-path: F:/image

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/furniture?serverTimezone=Asia/Shanghai
    username: root
    password: root

  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,file:${web.upload-path}
#枚举扫描
mybatis-plus:
  type-enums-package: com.gem.furniture.entity